[package]
name = "Data_Structures_and_Algorithms"
version = "0.1.0"
authors = ["Steven Leadbeater <info@ledsysconsultancy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
